### ISSUE TITLE
Schedule?

### ISSUE THREAD

**Issue by rossdakin** [18F/tech-talks#1]
This is great, @bsweger!

Is there a schedule of tech talks or calendar invite that folks can join?

**Comment by bsweger** [comment]
Great question @rossdakin. The tech talks are something that the 18F engineering team has been doing monthly--the queue is here:https://docs.google.com/document/d/1FQLUofvibixHXg0iiUIdF9Up8djUrUL4xqU64sxHg-U/edit

 There's definitely topics of broader 18F interest...paging @theresaanna, who runs the talks, to see if there's interest in extending the invites to a larger audience.

**Comment by theresaanna** [comment]
There absolutely is interest in widening the audience. We already have a few attendees who are not on the engineering team. I've just added the talks to the general onboarding docs on the hub so that anyone can find out about them, though the pull request isn't merged yet. If there are other ways to make them known across the org, I'm all ears!

@rossdakin I will add you to the invite. 

@bsweger Thanks for making this repo! I'll pull request add the schedule to the readme.
